### PR TITLE
Update TF providers

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Update TF_VERSION `0.15.5` -> `1.3.9` and update how the local providers are fetched and stored to be compatible with the latest TF specification.
```

### CODE REVIEW

**Comment by kevin-lacoo** [comment]
Hi @kon-angelo , How about alicloud?

**Comment by kon-angelo** [comment]
@kevin-lacoo I adapted to work with the new terraform update but I think you may be more qualified to evaluate a provider update

**Comment by kon-angelo** [comment]
/unhold

I performed the following tests for {aws,gcp,openstack,azure}:
- [x] successful integration test run
- [x] create infra
- [x] create infra with existing resources
- [x] reconcile and delete existing infra

**Review by shaoyongfeng — APPROVED** [review]

**Comment by shaoyongfeng** [comment]
Test is done on AliCLoud

**Review by MartinWeindel — APPROVED** [review]
/lgtm

**Review by dkistner — APPROVED** [review]

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
