### PR TITLE
update alicloud provider version

### PR DESCRIPTION
**Pull request by minchaow**
**What this PR does / why we need it**:
This PR is to update alicloud provider version to `1.84.0`, because in this version it fix the the issue: 

https://github.com/terraform-providers/terraform-provider-alicloud/issues/2399.

The fix is necessary for the enhancement: 

https://github.com/terraform-providers/terraform-provider-alicloud/issues/2399

**Which issue(s) this PR fixes**:
Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Release note**:

```noteworthy operator
Terraform version has been upgraded to `0.12.20`.
```

```improvement operator
Provider `alicloud` version has been upgraded to `1.84.0`.
```

### CODE REVIEW

**Comment by gardener-botmanager** [comment]
@ialidzhikov 

<details>
<summary>Message</summary>

> /cc @ialidzhikov 
</details>

**Comment by minchaow** [comment]
Not only updating the version of `alicloud` provider, but also need to update `terraform` version to `0.12.20`. Because current version `0.12.9` causes the bug, `alicloud_eip_association` is blocked and cannot be destroyed. In the version `0.12.20`, this bug has been fixed.

**Comment by rfranzke** [comment]
Just bumping the patch version of TF should be no risk, right @ialidzhikov ?

**Comment by ialidzhikov** [comment]
> Just bumping the patch version of TF should be no risk, right @ialidzhikov ?

We need to check the changelogs and probably test with all providers just to be sure.

@minchaow , can you update the issue you reference as in it you say that the affected terraform version is `v0.12.20` and in this PR you update to that version.

**Comment by rfranzke** [comment]
Yes, makes sense, thanks.
Once you approved @ialidzhikov we can go ahead with the merge + release. Before merging the update PR in the respective provider extension repositories we should do some testing with it.

**Comment by ialidzhikov** [comment]
For terraform-providers/terraform-provider-alicloud#2399 update

/status author-action

**Comment by minchaow** [comment]
@ialidzhikov: for issue [terraform-providers/terraform-provider-alicloud#2399](https://github.com/terraform-providers/terraform-provider-alicloud/issues/2399), I tested with latest version of provider, it has already been fixed. So I just closed this issue.

**Comment by ialidzhikov** [comment]
> @ialidzhikov: for issue [terraform-providers/terraform-provider-alicloud#2399](https://github.com/terraform-providers/terraform-provider-alicloud/issues/2399), I tested with latest version of provider, it has already been fixed. So I just closed this issue.

Thank you.

**Comment by ialidzhikov** [comment]
@minchaow , I actually reproduce the issue your described in https://github.com/terraform-providers/terraform-provider-alicloud/issues/2399. The first attempt to destroy always fails to delete `alicloud_eip_association.eip_natgw_asso_z0` with the same error from the issue and the second one succeeds. Was this the case also before this version bump?

**Comment by minchaow** [comment]
@ialidzhikov , For the problem in which cannot destroy `alicloud_eip_association.eip_natgw_asso_z0`, I think it is affected by `terraform`, not the `alicloud provider`. I can destroy the resources successfully with the version `0.12.20`, before the fix of issue [terraform-providers/terraform-provider-alicloud#2399](https://github.com/terraform-providers/terraform-provider-alicloud/issues/2399).

**Comment by ialidzhikov** [comment]
We had a short sync with @minchaow and he will try to reproduce.

**Comment by minchaow** [comment]
affected by issue https://github.com/gardener/gardener-extension-provider-alicloud/pull/94

**Pull request merged**
