### PR TITLE
Fix release test run

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area dev-productivity
/kind bug
/priority normal

**What this PR does / why we need it**:

In the `test-e2e` step during the release job the release tag will not exist on GitHub (yet), so we need to inject the current HEAD commit sha, so that the test-machinery can retrieve the current `TestDefinition`s from the repo.
Though, for the terraformer we still want to inject the docker image tag of the release, which should be tested.

This PR adapts the test run config and so on accordingly.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Review by dguendisch — APPROVED** [review]
/lgtm

**Review by schrodit — APPROVED** [review]

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
