### PR TITLE
Tag as latest published images

### LINKED ISSUE #28: latest tag points to version 0.1.0
Currently the examples do use image `eu.gcr.io/gardener-project/gardener/terraformer:latest`. However the latest tag points to version 0.1.0:

```
$ docker pull eu.gcr.io/gardener-project/gardener/terraformer:latest
latest: Pulling from gardener-project/gardener/terraformer
2fdfe1cd78c2: Pull complete
64917b29220a: Pull complete
2efdbc9a8eb4: Pull complete
c128a0d07fe2: Pull complete
Digest: sha256:4a67f524447498c59cf48696362f2d271d29f7e469b83c77a561f2b1d149bb66
Status: Downloaded newer image for eu.gcr.io/gardener-project/gardener/terraformer:latest
eu.gcr.io/gardener-project/gardener/terraformer:latest

$ docker images | grep terraformer | grep latest
eu.gcr.io/gardener-project/gardener/terraformer   latest       18688c3ead10        21 months ago 
   241MB
```

I would expect the latest tag to point to the latest release - 0.16.0 by the time of writing this.

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**:
Tag with `latest` the recently released image.

**Which issue(s) this PR fixes**:
Fixes #28 

**Special notes for your reviewer**:
/cc @rfranzke @ialidzhikov 
**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by vpnachev** [comment]
This change is influenced by https://github.com/gardener/gardener-extensions/blob/f82616ca422390e5d6d6f9106a7df1c84e2e66f8/.ci/pipeline_definitions#L40-L43

**Comment by vpnachev** [comment]
IMHO, I think it is fine to tag hotfix releases as well. Of course, they could point to hotfix of the non-latest minor release, e.g. latest points to `0.14.1`, while `0.15.0` has been released earlier.

This is how it works for g/gext.

**Comment by rfranzke** [comment]
No strong opinion TBH

**Comment by vpnachev** [comment]
Thanks @AndreasBurger @ialidzhikov @rfranzke!

**Pull request merged**
