### PR TITLE
Upgrade terraform to 0.15.5

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Upgrades terraform to 0.15.5. This is the final step of upgrading to 0.15 in order to fix the following issue gardener/gardener/issues/4838.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
* I ran successfully `make test-e2e` and `make docker-images` locally.
* I also ran successfully `make start` and `make start COMMAND=destroy` with a valid AWS configuration for one of my test shoots.
* I also ran successfully `make start` and `make start COMMAND=destroy` with a valid AWS configuration for one of my test shoots and an old state created with terraformer 0.12.31.
* For the provider validation status, see the comment below.

**Release note**:

```other operator
terraform has been upgraded to 0.15.5
```

### CODE REVIEW

**Comment by stoyanr** [comment]
AWS (see gardener/gardener-extension-provider-aws/pull/443):
- [x] reconciliation and deletion of existing Infrastructure (created with 0.12.31)
- [x] creation and deletion of new Infrastructure (single zone, new vpc)
- [x] creation and deletion of new Infrastructure (single zone, existing vpc)
- [x] creation and deletion of new Infrastructure (multiple zones, new vpc)
- [x] creation and deletion of new Infrastructure (multiple zone, existing vpc)
- [x] `gardener-extension-provider-aws` Infrastructure integration test

GCP (see gardener/gardener-extension-provider-gcp/pull/347):
- [x] reconciliation and deletion of existing Infrastructure (created with 0.12.31)
- [x] creation and deletion of new Infrastructure (single zone, new vpc)
- [x] creation and deletion of new Infrastructure (single zone, existing vpc)
- [x] `gardener-extension-provider-gcp` Infrastructure integration test

Azure (see gardener/gardener-extension-provider-azure/pull/394):
- [x] reconciliation and deletion of existing Infrastructure (created with 0.12.31)
- [x] creation and deletion of new Infrastructure

Alicloud (see gardener/gardener-extension-provider-alicloud/pull/381):
- [x] reconciliation and deletion of existing Infrastructure (created with 0.12.31)
- [x] creation and deletion of new Infrastructure

Openstack (see gardener/gardener-extension-provider-openstack/pull/352):
- [x] reconciliation and deletion of existing Infrastructure (created with 0.12.31)
- [x] creation and deletion of new Infrastructure

**Comment by stoyanr** [comment]
Rebased on top of latest master and removed `Draft`. This PR could be merged now (after approval).

**Comment by rfranzke** [comment]
Shall we merge this PR now @ialidzhikov?

**Comment by ialidzhikov** [comment]
I was able to double-check some of the items from https://github.com/gardener/terraformer/pull/107#issuecomment-963319550:
- provider-aws
  - Reconciliation of existing Infrastructure (with `0.12.31` state)
  - Deletion of existing Infrastructure (with `0.12.31` state)
  - Creation and deletion of new Infrastructure (single zone, new vpc)
  - Creation and deletion of new Infrastructure (multiple zones, new vpc)
  - Creation and deletion of new Infrastructure (single zone, existing vpc)
  - Creation and deletion of new Infrastructure (multiple zone, existing vpc)
  - provider-aws infrastructure integration test
  - Error code handling for Infrastructure deletion with VPC with infrastructure dependencies

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
