### PR TITLE
Enable kaniko and update golang to 1.16.2

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement
/priority normal

**What this PR does / why we need it**:
- Upgrades golang to 1.16.2
- Upgrades alpine to 3.13.2
- Enables the kaniko image build for the OCI images.

**Which issue(s) this PR fixes**:
Follow up on #82 as https://github.com/golang/go/issues/43985 has been fixed in golang 1.16.1

**Special notes for your reviewer**:

**Release note**:

```other developer
The golang has been updated to 1.16.2, the alpine has been updated to 3.13.2, as well as the CI/CD kaniko image build has been enabled for this repo.
```

### CODE REVIEW

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by vpnachev** [comment]
The verify job is failing because it is still using golang 1.15, I think we will need to merge this without successful checks.

**Review by timebertt — APPROVED** [review]
/lgtm

@rfranzke for "force-merge".

**Comment by vpnachev** [comment]
A friendly ping to @rfranzke.

**Comment by rfranzke** [comment]
Sorry for the delay

**Pull request merged**
