### PR TITLE
upgrade TF provider 1.124.2

### PR DESCRIPTION
**Pull request by minchaow**
**How to categorize this PR?**

/area open-source
/kind bug

**What this PR does / why we need it**:
This PR is to fix the issue of failing to SNatTableEntries because of flow control.
**Which issue(s) this PR fixes**:
Fixes #
https://github.com/aliyun/terraform-provider-alicloud/issues/3617
**Special notes for your reviewer**:

**Release note**:

```other operator
The following terraform provider plugin is updated:
- aliyun/terraform-provider-alicloud: 1.124.0 -> 1.124.2
```

### CODE REVIEW

**Review by vpnachev — COMMENTED** [review]
I see `1.124.2` is [released](https://github.com/aliyun/terraform-provider-alicloud/releases/tag/v1.124.2). Do you want to upgrade to it?

**Comment by minchaow** [comment]
> I see `1.124.2` is [released](https://github.com/aliyun/terraform-provider-alicloud/releases/tag/v1.124.2). Do you want to upgrade to it?

Good suggestion, I updated the provider to `1.124.2`

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by dkistner — APPROVED** [review]
/lgtm

**Pull request merged**
