### PR TITLE
Fix release test config/script

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area quality
/kind bug
/priority normal

**What this PR does / why we need it**:

During the release of `v2.0.0`, the `test-e2e` step failed because of some misconfigurations and required flags for the testrunner: see https://concourse.ci.gardener.cloud/teams/gardener/pipelines/terraformer-master/jobs/master-release-job/builds/1
This PR (hopefully) fixes the problem.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/invite @schrodit 

✅ depends on https://github.com/gardener/test-infra/pull/315

**Release note**:

```improvement operator

```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm
/second-opinion
/assign @schrodit

**Review by schrodit — APPROVED** [review]
a new testmachinery version that includes the adjustments is now released and deployed

**Pull request merged**
