### PR TITLE
Update azurerm provider

### PR DESCRIPTION
**Pull request by dkistner**
**How to categorize this PR?**

/kind enhancement
/priority normal

**What this PR does / why we need it**:
Update `azurerm` provider from 2.36.0 to 2.68.0

**Release note**:

```other operator
The terraform `azurerm` provider plugin is updated from `v2.36.0` to `v2.68.0`.
```

### CODE REVIEW

**Review by kon-angelo — APPROVED** [review]

**Comment by ialidzhikov** [comment]
Can you confirm that locally you played with the following cases and they all worked well?

- reconciliation of existing Infrastructure
- deletion of existing Infrastructure
- creation and deletion of new Infrastructure (zoned=false, new vnet)
- creation and deletion of new Infrastructure (zoned=true, new vnet)
- creation and deletion of new Infrastructure (zoned=false, existing vnet)

**Comment by kon-angelo** [comment]
@ialidzhikov , I tested the scenarios and they work.

For the new version to work we need to make an adaptation to the provider section and add this  `skip_provider_registration = "true"`.

**Comment by ialidzhikov** [comment]
> @ialidzhikov , I tested the scenarios and they work.

Thanks!

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by vpnachev** [comment]
/ For the new version to work we need to make an adaptation to the provider section and add this skip_provider_registration = "true".


Please, describe what needs to be done in a release note.

**Comment by ialidzhikov** [comment]
> @ialidzhikov , I tested the scenarios and they work.

Out of curiosity, how this scenario worked for you as I see that it does not work for me - https://github.com/gardener/gardener-extension-provider-azure/issues/359?

**Pull request merged**
